version: '3.5'

services:
  ar:
    build:
      context: '.'
    container_name: ar-app
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - "ar-db"
      - "ar-mail"
      - "ar-nodejs"
    networks:
      - app

  ar-db:
    image: mysql:8
    tty: true
    container_name: ar-db
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - app

  ar-mail:
    image: mailhog/mailhog:latest
    container_name: ar-mail
    ports:
      - "8125:8025"
      - "2525:1025"
    environment:
      - MT_USER=dashfluit
      - MT_PASSWD=dashfluit
      - MT_MAILBOX_LIMIT=512000001
      - MT_MESSAGE_LIMIT=102400001'
    networks:
      - app

  ar-redis:
    image: redis:latest
    container_name: ar-redis
    ports:
      - 6379:6379
    networks:
      - app

  ar-nodejs:  # Adicionando o serviço Node.js
    image: node:latest  # Use a versão do Node.js desejada
    container_name: ar-nodejs
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html/
    command: ["npm", "run", "dev"]  # Substitua pelo seu comando Vite
    ports:
     - 3009:3009
    depends_on:
      - "ar-db"
    networks:
      - app
networks:
  app:
    driver: bridge
